exclude: [".sass-cache/", ".jekyll-cache/", "gemfiles/",
          "Gemfile", "Gemfile.lock", "vendor/bundle/",
          "vendor/cache/", "vendor/gems/", "vendor/ruby/",
          "*.py", "components/*.html", "CSS/tin.css",
          "files/*.html", "files/*.txt", "*.md"
]